<?php

namespace App\Modules\AssetIdentifier\Services;

use App\Modules\Asset\Enums\IdentifierType;
use App\Modules\AssetIdentifier\Models\AssetIdentifier;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class AssetIdentifierService
{
    public function list(array $filters = []): LengthAwarePaginator
    {
        $perPage = (int) ($filters['per_page'] ?? 20);

        $query = AssetIdentifier::query()->with('asset');

        if (! empty($filters['asset_id'])) {
            $query->where('asset_id', $filters['asset_id']);
        }

        if (! empty($filters['identifier_type'])) {
            $query->where('identifier_type', $filters['identifier_type']);
        }

        if (! empty($filters['search'])) {
            $term = '%'.$filters['search'].'%';
            $operator = DB::connection()->getDriverName() === 'pgsql' ? 'ilike' : 'like';
            $query->where('identifier_value', $operator, $term);
        }

        return $query->orderByDesc('created_at')->paginate($perPage);
    }

    public function create(array $data): AssetIdentifier
    {
        if (($data['identifier_type'] ?? null) === IdentifierType::PSA_QR->value) {
            throw ValidationException::withMessages([
                'identifier_type' => ['The permanent PSA QR identifier is generated by the system and cannot be created manually.'],
            ]);
        }

        return DB::transaction(function () use ($data) {
            if (! empty($data['is_primary'])) {
                AssetIdentifier::query()
                    ->where('asset_id', $data['asset_id'])
                    ->update(['is_primary' => false]);
            }

            return AssetIdentifier::query()->create($data);
        });
    }

    public function update(AssetIdentifier $assetIdentifier, array $data): AssetIdentifier
    {
        if ($assetIdentifier->identifier_type === IdentifierType::PSA_QR) {
            throw ValidationException::withMessages([
                'identifier_value' => ['The permanent PSA QR identifier cannot be changed. Reprint its existing value instead.'],
            ]);
        }

        return DB::transaction(function () use ($assetIdentifier, $data) {
            if (! empty($data['is_primary'])) {
                AssetIdentifier::query()
                    ->where('asset_id', $data['asset_id'] ?? $assetIdentifier->asset_id)
                    ->where('id', '!=', $assetIdentifier->id)
                    ->update(['is_primary' => false]);
            }

            $assetIdentifier->update($data);

            return $assetIdentifier->fresh()->load('asset');
        });
    }

    public function delete(AssetIdentifier $assetIdentifier): void
    {
        if ($assetIdentifier->identifier_type === IdentifierType::PSA_QR) {
            throw ValidationException::withMessages([
                'identifier_value' => ['The permanent PSA QR identifier cannot be deleted.'],
            ]);
        }

        $assetIdentifier->delete();
    }

    public function findByValue(string $value): ?AssetIdentifier
    {
        $candidates = $this->candidateValues($value);

        $identifier = AssetIdentifier::query()
            ->with('asset')
            ->whereIn('identifier_value', $candidates)
            ->first();

        if ($identifier) {
            return $identifier;
        }

        // Direct Asset fallback lookup by asset_number or psa_qr_identifier
        $asset = \App\Modules\Asset\Models\Asset::query()
            ->whereIn('asset_number', $candidates)
            ->orWhereIn('psa_qr_identifier', $candidates)
            ->first();

        if (! $asset) {
            foreach ($candidates as $cand) {
                if (is_numeric($cand)) {
                    $asset = \App\Modules\Asset\Models\Asset::find((int) $cand);
                    if ($asset) {
                        break;
                    }
                }
            }
        }

        if ($asset) {
            $existing = AssetIdentifier::query()
                ->where('asset_id', $asset->id)
                ->first();

            if ($existing) {
                return $existing;
            }

            $newIdentifier = new AssetIdentifier();
            $newIdentifier->asset_id = $asset->id;
            $newIdentifier->identifier_type = IdentifierType::PSA_QR;
            $newIdentifier->identifier_value = $asset->psa_qr_identifier ?? $asset->asset_number;
            $newIdentifier->is_primary = true;
            $newIdentifier->setRelation('asset', $asset);

            return $newIdentifier;
        }

        return null;
    }

    /**
     * Accept official stored PSA QR value, pipe-separated payload strings,
     * direct asset numbers, and common unpadded scan inputs.
     */
    public function candidateValues(string $value): array
    {
        $value = trim($value);

        if ($value === '') {
            return [];
        }

        $candidates = [$value];

        if (str_contains($value, '|')) {
            $parts = explode('|', $value);
            foreach ($parts as $part) {
                $trimmed = trim($part);
                if ($trimmed !== '') {
                    $candidates[] = $trimmed;
                }
            }
        }

        foreach (array_values($candidates) as $cand) {
            if (preg_match('/^PSA-ASSET-(\d+)$/i', $cand, $matches) === 1) {
                $assetId = (int) $matches[1];
                if ($assetId > 0) {
                    $candidates[] = 'PSA-ASSET-'.str_pad((string) $assetId, 6, '0', STR_PAD_LEFT);
                    $candidates[] = (string) $assetId;
                }
            }
        }

        return array_values(array_unique($candidates));
    }
}
