<?php

namespace App\Modules\AssetIdentifier\Services;

use App\Modules\Asset\Enums\IdentifierType;
use App\Modules\AssetIdentifier\Models\AssetIdentifier;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class AssetIdentifierService
{
    public function list(array $filters = []): LengthAwarePaginator
    {
        $perPage = (int) ($filters['per_page'] ?? 20);

        $query = AssetIdentifier::query()->with('asset');

        if (! empty($filters['asset_id'])) {
            $query->where('asset_id', $filters['asset_id']);
        }

        if (! empty($filters['identifier_type'])) {
            $query->where('identifier_type', $filters['identifier_type']);
        }

        if (! empty($filters['search'])) {
            $term = '%'.$filters['search'].'%';
            $operator = DB::connection()->getDriverName() === 'pgsql' ? 'ilike' : 'like';
            $query->where('identifier_value', $operator, $term);
        }

        return $query->orderByDesc('created_at')->paginate($perPage);
    }

    public function create(array $data): AssetIdentifier
    {
        if (($data['identifier_type'] ?? null) === IdentifierType::PSA_QR->value) {
            throw ValidationException::withMessages([
                'identifier_type' => ['The permanent PSA QR identifier is generated by the system and cannot be created manually.'],
            ]);
        }

        return DB::transaction(function () use ($data) {
            if (! empty($data['is_primary'])) {
                AssetIdentifier::query()
                    ->where('asset_id', $data['asset_id'])
                    ->update(['is_primary' => false]);
            }

            return AssetIdentifier::query()->create($data);
        });
    }

    public function update(AssetIdentifier $assetIdentifier, array $data): AssetIdentifier
    {
        if ($assetIdentifier->identifier_type === IdentifierType::PSA_QR) {
            throw ValidationException::withMessages([
                'identifier_value' => ['The permanent PSA QR identifier cannot be changed. Reprint its existing value instead.'],
            ]);
        }

        return DB::transaction(function () use ($assetIdentifier, $data) {
            if (! empty($data['is_primary'])) {
                AssetIdentifier::query()
                    ->where('asset_id', $data['asset_id'] ?? $assetIdentifier->asset_id)
                    ->where('id', '!=', $assetIdentifier->id)
                    ->update(['is_primary' => false]);
            }

            $assetIdentifier->update($data);

            return $assetIdentifier->fresh()->load('asset');
        });
    }

    public function delete(AssetIdentifier $assetIdentifier): void
    {
        if ($assetIdentifier->identifier_type === IdentifierType::PSA_QR) {
            throw ValidationException::withMessages([
                'identifier_value' => ['The permanent PSA QR identifier cannot be deleted.'],
            ]);
        }

        $assetIdentifier->delete();
    }

    public function findByValue(string $value): ?AssetIdentifier
    {
        return AssetIdentifier::query()
            ->with('asset')
            ->whereIn('identifier_value', $this->candidateValues($value))
            ->first();
    }

    /**
     * Accept the official stored PSA QR value and common unpadded scan input
     * without changing the permanent identifier stored in the database.
     */
    public function candidateValues(string $value): array
    {
        $value = trim($value);

        if ($value === '') {
            return [];
        }

        $candidates = [$value];
        $reference = strtok($value, '|') ?: $value;

        if ($reference !== $value) {
            $candidates[] = $reference;
        }

        if (preg_match('/^PSA-ASSET-(\d+)$/i', $reference, $matches) === 1) {
            $assetId = (int) $matches[1];

            if ($assetId > 0) {
                $candidates[] = 'PSA-ASSET-'.str_pad((string) $assetId, 6, '0', STR_PAD_LEFT);
            }
        }

        return array_values(array_unique($candidates));
    }
}
