export interface PlaceholderGroup {
  category: string
  items: { token: string; label: string; example: string }[]
}

export const SUPPORTED_PLACEHOLDERS: PlaceholderGroup[] = [
  {
    category: 'Employee',
    items: [
      { token: '{{employee_name}}', label: 'Employee Name', example: 'Juan Dela Cruz' },
      { token: '{{employee_number}}', label: 'Employee Number', example: '20250012' },
      { token: '{{department}}', label: 'Department', example: 'Information Technology Division' },
      { token: '{{office}}', label: 'Office', example: 'PSA Central Office' },
    ],
  },
  {
    category: 'Asset',
    items: [
      { token: '{{asset_name}}', label: 'Asset Name', example: 'Dell Latitude 5420 Laptop' },
      { token: '{{asset_code}}', label: 'Asset / Property Code', example: 'PSA-LAP-2026-0042' },
      { token: '{{serial_number}}', label: 'Serial Number', example: 'SN-994810234' },
      { token: '{{manufacturer}}', label: 'Manufacturer', example: 'Dell Technologies' },
      { token: '{{category}}', label: 'Category', example: 'IT Equipment' },
      { token: '{{condition}}', label: 'Condition Status', example: 'Good' },
    ],
  },
  {
    category: 'Borrowing',
    items: [
      { token: '{{borrow_date}}', label: 'Borrow Date', example: '2026-07-28' },
      { token: '{{due_date}}', label: 'Due Date', example: '2026-08-11' },
      { token: '{{returned_date}}', label: 'Returned Date', example: '2026-08-05' },
      { token: '{{requested_extension}}', label: 'Requested Extension Date', example: '2026-08-25' },
      { token: '{{approved_extension}}', label: 'Approved Extension Date', example: '2026-08-25' },
    ],
  },
  {
    category: 'System',
    items: [
      { token: '{{current_date}}', label: 'Current Date', example: new Date().toLocaleDateString() },
      { token: '{{current_time}}', label: 'Current Time', example: new Date().toLocaleTimeString() },
      { token: '{{prepared_by}}', label: 'Prepared By Name', example: 'Maria Santos' },
      { token: '{{generated_by}}', label: 'Generated By User', example: 'System Administrator' },
    ],
  },
]
