import { useState } from 'react'
import { Tag, Search, Plus } from 'lucide-react'

export interface PlaceholderGroup {
  category: string
  items: { token: string; label: string; example: string }[]
}

export const SUPPORTED_PLACEHOLDERS: PlaceholderGroup[] = [
  {
    category: 'Employee',
    items: [
      { token: '{{employee_name}}', label: 'Employee Name', example: 'Juan Dela Cruz' },
      { token: '{{employee_number}}', label: 'Employee Number', example: '20250012' },
      { token: '{{department}}', label: 'Department', example: 'Information Technology Division' },
      { token: '{{office}}', label: 'Office', example: 'PSA Central Office' },
    ],
  },
  {
    category: 'Asset',
    items: [
      { token: '{{asset_name}}', label: 'Asset Name', example: 'Dell Latitude 5420 Laptop' },
      { token: '{{asset_code}}', label: 'Asset / Property Code', example: 'PSA-LAP-2026-0042' },
      { token: '{{serial_number}}', label: 'Serial Number', example: 'SN-994810234' },
      { token: '{{manufacturer}}', label: 'Manufacturer', example: 'Dell Technologies' },
      { token: '{{category}}', label: 'Category', example: 'IT Equipment' },
      { token: '{{condition}}', label: 'Condition Status', example: 'Good' },
    ],
  },
  {
    category: 'Borrowing',
    items: [
      { token: '{{borrow_date}}', label: 'Borrow Date', example: '2026-07-28' },
      { token: '{{due_date}}', label: 'Due Date', example: '2026-08-11' },
      { token: '{{returned_date}}', label: 'Returned Date', example: '2026-08-05' },
      { token: '{{requested_extension}}', label: 'Requested Extension Date', example: '2026-08-25' },
      { token: '{{approved_extension}}', label: 'Approved Extension Date', example: '2026-08-25' },
    ],
  },
  {
    category: 'System',
    items: [
      { token: '{{current_date}}', label: 'Current Date', example: new Date().toLocaleDateString() },
      { token: '{{current_time}}', label: 'Current Time', example: new Date().toLocaleTimeString() },
      { token: '{{prepared_by}}', label: 'Prepared By Name', example: 'Maria Santos (Property Custodian)' },
      { token: '{{generated_by}}', label: 'Generated By User', example: 'System Administrator' },
    ],
  },
]

interface PlaceholderPickerProps {
  onInsert: (token: string) => void
}

export function PlaceholderPicker({ onInsert }: PlaceholderPickerProps) {
  const [search, setSearch] = useState('')

  const filteredGroups = SUPPORTED_PLACEHOLDERS.map((group) => ({
    ...group,
    items: group.items.filter(
      (item) =>
        item.token.toLowerCase().includes(search.toLowerCase()) ||
        item.label.toLowerCase().includes(search.toLowerCase()) ||
        item.example.toLowerCase().includes(search.toLowerCase())
    ),
  })).filter((group) => group.items.length > 0)

  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-3.5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-1.5 font-semibold text-xs text-slate-700 uppercase tracking-wider">
          <Tag size={14} className="text-[#0D47A1]" />
          <span>Insert Placeholders</span>
        </div>
        <span className="text-[11px] text-slate-400">Click any token to insert into template body</span>
      </div>

      {/* Search Input */}
      <div className="relative mb-3">
        <Search size={14} className="absolute left-3 top-2.5 text-slate-400" />
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search placeholders (e.g. employee, asset code)..."
          className="w-full rounded-lg border border-slate-200 bg-white py-1.5 pl-8 pr-3 text-xs text-slate-800 placeholder-slate-400 focus:border-[#0D47A1] focus:outline-none"
        />
      </div>

      {/* Categories */}
      <div className="space-y-3 max-h-56 overflow-y-auto pr-1">
        {filteredGroups.length === 0 ? (
          <p className="py-2 text-center text-xs text-slate-400">No matching placeholders found.</p>
        ) : (
          filteredGroups.map((group) => (
            <div key={group.category}>
              <p className="mb-1 text-[11px] font-bold uppercase tracking-wider text-slate-500">
                {group.category}
              </p>
              <div className="grid gap-1.5 sm:grid-cols-2">
                {group.items.map((item) => (
                  <button
                    key={item.token}
                    type="button"
                    onClick={() => onInsert(item.token)}
                    className="flex items-center justify-between rounded-lg border border-slate-200 bg-white p-2 text-left transition-all hover:border-[#0D47A1] hover:bg-[#EFF6FF] hover:shadow-xs group"
                  >
                    <div>
                      <div className="font-mono text-[11.5px] font-semibold text-[#0D47A1]">
                        {item.token}
                      </div>
                      <div className="text-[11px] text-slate-500">{item.label}</div>
                    </div>
                    <Plus size={14} className="text-slate-300 transition-colors group-hover:text-[#0D47A1]" />
                  </button>
                ))}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}
